sudo: true
language: ruby
rvm:
  - 2.4.0
before_install: 
  - gem install bundler -v 1.16.0
  - bundle install
install:
  - sudo pip install xml2rfc
script:
  - bundle exec rspec --color --format documentation --require spec_helper 
